### ISSUE TITLE
[Enhancement]: Please update to new release

### ISSUE THREAD

**Issue by MartinMiller** [diddlesnaps/openra#26]
### What changes would you like?

New release since 10th of october 2023. Needs to be updated. Ty

**Comment by eslerm** [comment]
likely resolved by https://github.com/diddlesnaps/openra/pull/25

**Comment by MartinMiller** [comment]
no still the same
channels:
  latest/stable:    release-20230225  2023-03-08 (1403) 147MB -
  latest/candidate: ↑                                         
  latest/beta:      release-20230225  2023-03-06 (1403) 147MB -
  latest/edge:      playtest-20230218 2023-03-06 (1401) 147MB -
  installed:          release-20230225             (1403) 147MB -

**Comment by lucyllewy** [comment]
The 20231010 release should now be available in stable (and beta) channels, and the 20230927 playtest should be available in the edge channel.

**Comment by MartinMiller** [comment]
Many thanks for your efforts
